services:
  db:
    image: postgres:13-alpine
    container_name: flying_dishes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flying_dishes
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: flying_dishes_backend
    ports:
      - "8001:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/flying_dishes"
      PORT: 8080
    command: ["/bin/sh", "-c", "python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8080"]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: flying_dishes_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: {}
