services:
  db:
    image: postgres:13-alpine
    container_name: flying_dishes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flying_dishes
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./  # cartella con Dockerfile
      dockerfile: Dockerfile
    container_name: flying_dishes_backend
    ports:
      - "8001:8080"  # cambia a 8080 per Cloud Run compatibilit√†
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/flying_dishes"
      PORT: 8080  # aggiungi questo!
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    user: "0:0"  # ROOT per Windows!
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro


volumes:
  postgres_data:
